controllers:
    resource: ../src/Controller/
    type: attribute

homepage:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /link/check
        permanent: true